name: ammonite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.9+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "/Users/arunhegde/Developer/AppIcon.appiconset/iphone180.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "/Users/arunhegde/Developer/AppIcon.appiconset/iphone180.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "/Users/arunhegde/Developer/AppIcon.appiconset/mac1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "/Users/arunhegde/Developer/AppIcon.appiconset/mac1024.png"
